accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("login/",views.login_user, name="login"),
    path("profile/",views.profile_user, name="profile"),
    path("register/",views.register_user, name="register"),
    path("logout/",views.logout_user, name="logout"),
    
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views
from django.conf import settings

app_name = 'app'



urlpatterns = [
    path('', views.home, name='home'),
    path('admin-site/dashboard/', views.dashboard, name='dashboard'),
    path('view/thesis/', views.view_thesis, name='view_thesis'),
    path('view/memories/', views.view_memories, name='view_memories'),
    path('view/details/<str:document_type>/<int:document_id>/', views.document_details, name='document_details'),
    path('add/comment/<str:document_type>/<int:document_id>/', views.add_comment, name='add_comment'),
    path('delete/comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('add/thesis/', views.add_thesis, name='add_thesis'),
    path('add/memory/', views.add_memory, name='add_memory'),
    path('blog/', views.blog, name='blog'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    
    

]

publish/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls,),
    path('accounts/',include('accounts.urls')),
    path('',include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/site/components/navbar.html
{% load static %}
<nav class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom">
  <div class="container-fluid">
    {% comment %}search bar dekstop{% endcomment %}
    <nav class="navbar navbar-header-left navbar-expand-lg navbar-form nav-search p-0 d-none d-lg-flex">
      <form action="{% url 'app:home' %}" method="get">
        <div class="input-group">
          <div class="input-group-prepend">
            <button type="submit" class="btn btn-search pe-1"><i class="fa fa-search search-icon"></i></button>
          </div>
          <input type="text" id="search" name="search" placeholder="Rechercher..." class="form-control" />
        </div>
      </form>
    </nav>

    <ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
      <li class="nav-item topbar-icon dropdown hidden-caret d-flex d-lg-none">
        {% comment %}serach bar responsive{% endcomment %}
        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" aria-haspopup="true"><i class="fa fa-search"></i></a>

        <ul class="dropdown-menu dropdown-search animated fadeIn">
          <form class="navbar-left navbar-form nav-search">
            <div class="input-group">
              <input type="text" placeholder="Search ..." class="form-control" />
            </div>
          </form>
        </ul>
      </li>
      {% comment %}
      <li class="nav-item topbar-icon dropdown hidden-caret">
        <a class="nav-link dropdown-toggle" href="#" id="messageDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-envelope"></i></a>
        <ul class="dropdown-menu messages-notif-box animated fadeIn" aria-labelledby="messageDropdown">
          <li>
            <div class="dropdown-title d-flex justify-content-between align-items-center">
              Messages
              <a href="#" class="small">Mark all as read</a>
            </div>
          </li>
          <li>
            <div class="message-notif-scroll scrollbar-outer">
              <div class="notif-center">
                <a href="#">
                  <div class="notif-img">
                    <img src="assets/img/jm_denis.jpg" alt="Img Profile" />
                  </div>
                  <div class="notif-content">
                    <span class="subject">Jimmy Denis</span>
                    <span class="block">How are you ?</span>
                    <span class="time">5 minutes ago</span>
                  </div>
                </a>
                <a href="#">
                  <div class="notif-img">
                    <img src="assets/img/chadengle.jpg" alt="Img Profile" />
                  </div>
                  <div class="notif-content">
                    <span class="subject">Chad</span>
                    <span class="block">Ok, Thanks !</span>
                    <span class="time">12 minutes ago</span>
                  </div>
                </a>
                <a href="#">
                  <div class="notif-img">
                    <img src="assets/img/mlane.jpg" alt="Img Profile" />
                  </div>
                  <div class="notif-content">
                    <span class="subject">Jhon Doe</span>
                    <span class="block">Ready for the meeting today...</span>
                    <span class="time">12 minutes ago</span>
                  </div>
                </a>
                <a href="#">
                  <div class="notif-img">
                    <img src="assets/img/talha.jpg" alt="Img Profile" />
                  </div>
                  <div class="notif-content">
                    <span class="subject">Talha</span>
                    <span class="block">Hi, Apa Kabar ?</span>
                    <span class="time">17 minutes ago</span>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <li>
            <a class="see-all" href="javascript:void(0);">See all messages<i class="fa fa-angle-right"></i></a>
          </li>
        </ul>
      </li>
      {% endcomment %} {% comment %}
      <li class="nav-item topbar-icon dropdown hidden-caret">
        <a class="nav-link dropdown-toggle" href="#" id="notifDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-bell"></i>
          <span class="notification">4</span>
        </a>
        <ul class="dropdown-menu notif-box animated fadeIn" aria-labelledby="notifDropdown">
          <li>
            <div class="dropdown-title">You have 4 new notification</div>
          </li>
          <li>
            <div class="notif-scroll scrollbar-outer">
              <div class="notif-center">
                <a href="#">
                  <div class="notif-icon notif-primary">
                    <i class="fa fa-user-plus"></i>
                  </div>
                  <div class="notif-content">
                    <span class="block">New user registered</span>
                    <span class="time">5 minutes ago</span>
                  </div>
                </a>
                <a href="#">
                  <div class="notif-icon notif-success">
                    <i class="fa fa-comment"></i>
                  </div>
                  <div class="notif-content">
                    <span class="block">Rahmad commented on Admin</span>
                    <span class="time">12 minutes ago</span>
                  </div>
                </a>
                <a href="#">
                  <div class="notif-img">
                    <img src="assets/img/profile2.jpg" alt="Img Profile" />
                  </div>
                  <div class="notif-content">
                    <span class="block">Reza send messages to you</span>
                    <span class="time">12 minutes ago</span>
                  </div>
                </a>
                <a href="#">
                  <div class="notif-icon notif-danger">
                    <i class="fa fa-heart"></i>
                  </div>
                  <div class="notif-content">
                    <span class="block">Farrah liked Admin</span>
                    <span class="time">17 minutes ago</span>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <li>
            <a class="see-all" href="javascript:void(0);">See all notifications<i class="fa fa-angle-right"></i></a>
          </li>
        </ul>
      </li>
      {% endcomment %} {% comment %}queek actions{% comment %}
      <li class="nav-item topbar-icon dropdown hidden-caret">
        <a class="nav-link" data-bs-toggle="dropdown" href="#" aria-expanded="false"><i class="fas fa-layer-group"></i></a>
        <div class="dropdown-menu quick-actions animated fadeIn">
          <div class="quick-actions-header">
            <span class="title mb-1">Quick Actions</span>
            <span class="subtitle op-7">Shortcuts</span>
          </div>
          <div class="quick-actions-scroll scrollbar-outer">
            <div class="quick-actions-items">
              <div class="row m-0">
                <a class="col-6 col-md-4 p-0" href="#">
                  <div class="quick-actions-item">
                    <div class="avatar-item bg-danger rounded-circle">
                      <i class="far fa-calendar-alt"></i>
                    </div>
                    <span class="text">Calendar</span>
                  </div>
                </a>
                <a class="col-6 col-md-4 p-0" href="#">
                  <div class="quick-actions-item">
                    <div class="avatar-item bg-warning rounded-circle">
                      <i class="fas fa-map"></i>
                    </div>
                    <span class="text">Maps</span>
                  </div>
                </a>
                <a class="col-6 col-md-4 p-0" href="#">
                  <div class="quick-actions-item">
                    <div class="avatar-item bg-info rounded-circle">
                      <i class="fas fa-file-excel"></i>
                    </div>
                    <span class="text">Reports</span>
                  </div>
                </a>
                <a class="col-6 col-md-4 p-0" href="#">
                  <div class="quick-actions-item">
                    <div class="avatar-item bg-success rounded-circle">
                      <i class="fas fa-envelope"></i>
                    </div>
                    <span class="text">Emails</span>
                  </div>
                </a>
                <a class="col-6 col-md-4 p-0" href="#">
                  <div class="quick-actions-item">
                    <div class="avatar-item bg-primary rounded-circle">
                      <i class="fas fa-file-invoice-dollar"></i>
                    </div>
                    <span class="text">Invoice</span>
                  </div>
                </a>
                <a class="col-6 col-md-4 p-0" href="#">
                  <div class="quick-actions-item">
                    <div class="avatar-item bg-secondary rounded-circle">
                      <i class="fas fa-credit-card"></i>
                    </div>
                    <span class="text">Payments</span>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </li>
      {% endcomment %} {% comment %}user information{% endcomment %}
      <li class="nav-item topbar-user dropdown hidden-caret">
        <a class="dropdown-toggle profile-pic" data-bs-toggle="dropdown" href="#" aria-expanded="false">
          <div class="avatar-sm">
            <img src="{{ user.profile_photo.url }} " alt="..." class="avatar-img rounded-circle" />
          </div>
          <span class="profile-username">
            <span class="op-7">Salut,</span>
            <span class="fw-bold">{{ user.username }}</span>
          </span>
        </a>
        <ul class="dropdown-menu dropdown-user animated fadeIn">
          <div class="dropdown-user-scroll scrollbar-outer">
            <li>
              <div class="user-box">
                <div class="avatar-lg">
                  <img src=" {% static 'assets/img/profile.jpg' %}" alt="image profile" class="avatar-img rounded" />
                </div>
                <div class="u-text">
                  <h4>{{ user.username }}</h4>
                  <p class="text-muted">{{ user.email }}</p>
                  <a href="profile.html" class="btn btn-xs btn-secondary btn-sm">Voir le profil</a>
                </div>
              </div>
            </li>
            <li>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Mon profil</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">Se Déconnecter</a>
            </li>
          </div>
        </ul>
      </li>
    </ul>
  </div>
</nav>

templates/app/site/components/sidebar.html
{% load static %}
<div class="sidebar" data-background-color="dark">
  <div class="sidebar-logo">
    <!-- Logo Header -->
    <div class="logo-header mt-4" data-background-color="dark">
      <a href="index.html" class="logo"><img src=" {% static 'assets/img/binda-log.png' %} " alt="navbar brand" class="navbar-brand" height="100" /></a>
      <div class="nav-toggle">
        <button class="btn btn-toggle toggle-sidebar"><i class="gg-menu-right"></i></button>
        <button class="btn btn-toggle sidenav-toggler"><i class="gg-menu-left"></i></button>
      </div>
      <button class="topbar-toggler more"><i class="gg-more-vertical-alt"></i></button>
    </div>
    <!-- End Logo Header -->
  </div>
  <div class="sidebar-wrapper scrollbar scrollbar-inner">
    <div class="sidebar-content">
      <ul class="nav nav-secondary">
        <li class="nav-item 
        {% if active_home %}
            {{ active_home }}
          {% endif %}
           ">
          <a href="{% url 'app:home' %}">
            <i class="fas fa-home"></i>
            <p>Home</p>
          </a>
        </li>
        <li class="nav-item  {% if active_thesis or active_memory %}
          active sub-menu
        {% endif %}">
          <a data-bs-toggle="collapse" href="#tables">
            <i class="fas fa-book"></i>
            <p>Document</p>
            <span class="caret"></span>
          </a>
          <div class="collapse  {% if active_thesis or active_memory %}
          show
        {% endif %}" id="tables">
            <ul class="nav nav-collapse">
              <li class="{% if active_thesis %}
          active
        {% endif %}">
                <a href="{% url 'app:view_thesis' %}"><span class="sub-item">Thèse</span></a>
              </li>
              <li class="{% if active_memory %}
          active
        {% endif %}">
                <a href="{% url 'app:view_memories' %}"><span class="sub-item">Mémoire</span></a>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>