app/urls.py
from django.urls import path
from . import views
from django.conf import settings

app_name = 'app'



urlpatterns = [
    path('', views.home, name='home'),
    path('admin-site/dashboard/', views.dashboard, name='dashboard'),
    path('view/thesis/', views.view_thesis, name='view_thesis'),
    path('view/memories/', views.view_memories, name='view_memories'),
    path('view/details/<str:document_type>/<int:document_id>/', views.document_details, name='document_details'),
    path('add/comment/<str:document_type>/<int:document_id>/', views.add_comment, name='add_comment'),
    path('delete/comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('add/thesis/', views.add_thesis, name='add_thesis'),
    path('add/memory/', views.add_memory, name='add_memory'),
    path('blog/', views.blog, name='blog'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    
    

]

publish/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls,),
    path('accounts/',include('accounts.urls')),
    path('',include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/site/pages/add_memory.html
{% extends "app/site/base.html" %}
{% load static %}

{% block container %}
    <div class="page-inner">
    <div class="page-header">
        <h3 class="fw-bold mb-3">Gestions des mémoires</h3>
        <ul class="breadcrumbs mb-3">
            <li class="nav-home">
                <a href="{% url 'app:home' %}">
                    <i class="icon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="icon-arrow-right"></i>
            </li>
            <li class="nav-item">
                <a href="#">Documents</a>
            </li>
            <li class="separator">
                <i class="icon-arrow-right"></i>
            </li>
            <li class="nav-item">
                <a href="{% url 'app:view_memories' %}">Mémoires</a>
            </li>
        </ul>

    </div>  
    
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Remplissez ce formulaire</div>
                </div>
                <div class="card-body">
                    <form action="{% url 'app:add_memory' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                      <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="title">Titre</label>
                                    <input
                                        type="text"
                                        class="form-control"
                                        id="title"
                                        name="title"
                                        placeholder="Entrez le titre du document"
                                        required
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <textarea class="form-control" name="description" id="description" rows="5"></textarea>
                                </div>

                                

                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="image">Image</label>
                                    <input
                                        type="file"
                                        class="form-control"
                                        id="image"
                                        name="image"
                                        required
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="resume">Résumé</label>
                                    <textarea class="form-control" name="resume" id="resume" rows="5"></textarea>
                                </div>

                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="file">Fichier pdf</label>
                                    <input
                                        type="file"
                                        class="form-control"
                                        id="file"
                                        name="file"
                                        accept=".pdf"
                                        required
                                    />
                                </div>

                            </div>
                      </div>
                       <div class="card-action">
                             <button class="btn btn-success rounded" type="submit">Publier</button>
                       </div>
                 </form>
                </div>
            </div>
    </div>
</div>
{% endblock container %}
    

templates/app/site/pages/add_thesis.html
{% extends "app/site/base.html" %}
{% load static %}

{% block container %}
    <div class="page-inner">
    <div class="page-header">
        <h3 class="fw-bold mb-3">Gestions des thèses</h3>
        <ul class="breadcrumbs mb-3">
            <li class="nav-home">
                <a href="{% url 'app:home' %}">
                    <i class="icon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="icon-arrow-right"></i>
            </li>
            <li class="nav-item">
                <a href="#">Documents</a>
            </li>
            <li class="separator">
                <i class="icon-arrow-right"></i>
            </li>
            <li class="nav-item">
                <a href="{% url 'app:view_thesis' %}">Thèses</a>
            </li>
        </ul>

    </div>  
    
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Remplissez ce formulaire</div>
                </div>
                <div class="card-body">
                    <form action="{% url 'app:add_thesis' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                      <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="title">Titre</label>
                                    <input
                                        type="text"
                                        class="form-control"
                                        id="title"
                                        name="title"
                                        placeholder="Entrez le titre du document"
                                        required
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <textarea class="form-control" name="description" id="description" rows="5"></textarea>
                                </div>

                                

                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="image">Image</label>
                                    <input
                                        type="file"
                                        class="form-control"
                                        id="image"
                                        name="image"
                                        required
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="resume">Résumé</label>
                                    <textarea class="form-control" name="resume" id="resume" rows="5"></textarea>
                                </div>

                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="file">Fichier pdf</label>
                                    <input
                                        type="file"
                                        class="form-control"
                                        id="file"
                                        name="file"
                                        accept=".pdf"
                                        required
                                    />
                                </div>

                            </div>
                      </div>
                       <div class="card-action">
                             <button class="btn btn-success rounded" type="submit">Publier</button>
                       </div>
                 </form>
                </div>
            </div>
    </div>
</div>
{% endblock container %}
    

templates/app/site/pages/home.html
{% extends "app/site/base.html" %}
{% load static %}


{% block container %}
<div class="page-inner">
    <div class="row">
        <div class="col-md-12">
            
            {% if count_search %}
                <p class="lead">{{count_search}}</p>
            {% endif %}

            {% if messages %}
                            {% for message in messages %}
                                <div class="alert ml-3  mr-3
                                    {% if message.tags == 'success' %}
                                        alert-success
                                    {% elif message.tags == 'error'  %}
                                    alert-danger
                                    {% endif %}

                                        ">
                                        {{message}}
                                    </div>
                            {% endfor %}
                            {% endif %}
                
            <div class="card card-info card-annoucement card-round">
                <div class="card-body text-right">
                <div class="card-opening h1 fw-bold">Bienvenue sur  Binda,</div>
                    <div class="card-desc text-left">
                        Accédez à une vaste bibliothèque de travaux académiques, explorez les recherches ménées par des étudiants, 
                        chercheurs et enseignants de la <span class="fw-bold">HEC GOMBE</span> ou soumettez votre propre thèse ou mémoire.
                    </div>
                    <div class="card-detail">
                        <div class="btn btn-light btn-rounded">Voir plus</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Les dernières publications</div>
                </div>
                <div class="card-body">
                    {% comment %} Les cartes {% endcomment %}
                    <div class="row">
                        {% comment %} ------------------------------------ {% endcomment %}
                        
                        {% if documents %}
                        {% for document in documents %}
                        <div class="col-md-4">
                            <div class="card card-post card-round">
                                <img
                                    class="card-img-top"
                                    src="{{document.image.url}}"
                                    alt="Card image cap"
                                />
                                <div class="card-body">
                                    <div class="d-flex">
                                        <div class="avatar">
                                            {% if  document.author.profile_photo %}
                                            <img
                                            src={{document.author.profile_photo.url}}
                                            alt="..."
                                            class="avatar-img rounded-circle"
                                            />
                                            {% else %}
                                              <i class="fas fa-user fs-5"></i>
                                            {% endif %}
                                          
                                        </div>
                                        <div class="info-post ms-2">
                                            <p class="username">{{document.author.username}} 
                                            {% if user == document.author %}
                                                <small class="ml-2">(Vous)</small>
                                            {% endif %}
                                                </p>
                                            <p class="date text-muted">{{document.date_publication}}</p>
                                        </div>
                                    </div>
                                    <div class="separator-solid"></div>
                                    <p class="card-category text-info mb-1">
                                    
                                    {% if document.author.is_student %}
                                        <a href="#">Etudiant</a> 
                                    {% elif document.author.is_academic_personal %}
                                        <a href="#">Personel Académique</a>
                                    {% elif document.author.is_seacher %}
                                        <a href="#">Chercheur</a>
                                    {% else %}
                                    <a href="">Non précisé</a>
                                    {% endif %}
                                        
                                    </p>
                                    <h3 class="card-title">
                                    <a href="#"> {{document.title}} </a>
                                    </h3>
                                    <p class="card-text">
                                    {{document.description}}
                                    </p>
                                    
                                    {% if document.document_type == 'Thesis' %}
                                        <a href="{% url 'app:document_details' 'thesis' document.id %}" class="btn btn-primary btn-rounded btn-sm"
                                    >Voir plus</a
                                    >
                                    {% elif document.document_type == 'Memory' %}
                                        <a href="{% url 'app:document_details' 'memory' document.id %}" class="btn btn-primary btn-rounded btn-sm"
                                        >Voir plus</a
                                        >
                                    {% endif %}
                                        
                                    
                                </div>
                            </div>
                        </div>

                        {% endfor %}
                        {% else %}
                         <p>
                            Pas des publications trouvées 
                         </p>
                        {% endif %}
                            
                     
                        {% comment %} ------------------------------------ {% endcomment %}
                   
                    </div>
                    
                </div>
            </div>
    </div>
</div>

    
{% endblock container %}
    

templates/app/site/pages/view_memories.html
{% extends "app/site/base.html" %}
{% load static %}

{% block container %}
    <div class="page-inner">
    <div class="page-header">
        <h3 class="fw-bold mb-3">Mémoires</h3>
        <ul class="breadcrumbs mb-3">
            <li class="nav-home">
                <a href="{% url 'app:home' %}">
                    <i class="icon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="icon-arrow-right"></i>
            </li>
            <li class="nav-item">
                <a href="#">Documents</a>
            </li>
            <li class="separator">
                <i class="icon-arrow-right"></i>
            </li>
            <li class="nav-item">
                <a href="{% url 'app:view_memories' %}">Mémoires</a>
            </li>
        </ul>

        <div class="ms-md-auto py-2 py-md-0">
            <a href="{% url 'app:add_memory' %}" class="btn btn-label-info btn-round me-2">Publier</a>
        </div>

    </div>  
    
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Toutes les thèses</div>
                </div>
                <div class="card-body">
                    {% comment %} Les cartes {% endcomment %}
                    <div class="row">
                        {% comment %} ------------------------------------ {% endcomment %}
                        
                        {% if documents %}
                        {% for document in documents %}
                        <div class="col-md-4">
                            <div class="card card-post card-round">
                                <img
                                    class="card-img-top"
                                    src="{{document.image.url}}"
                                    alt="Card image cap"
                                />
                                <div class="card-body">
                                    <div class="d-flex">
                                        <div class="avatar">
                                            {% if  document.author.profile_photo %}
                                            <img
                                            src="{{document.author.profile_photo.url}}"
                                            alt="..."
                                            class="avatar-img rounded-circle"
                                            />
                                            {% else %}
                                              <i class="fas fa-user fs-5"></i>
                                            {% endif %}
                                          
                                        </div>
                                        <div class="info-post ms-2">
                                            <p class="username">{{document.author.username}} 
                                            {% if user == document.author %}
                                                <small class="ml-2">(Vous)</small>
                                            {% endif %}
                                                </p>
                                            <p class="date text-muted">{{document.date_publication}}</p>
                                        </div>
                                    </div>
                                    <div class="separator-solid"></div>
                                    <p class="card-category text-info mb-1">
                                    
                                    {% if document.author.is_student %}
                                        <a href="#">Etudiant</a> 
                                    {% elif document.author.is_academic_personal %}
                                        <a href="#">Personel Académique</a>
                                    {% elif document.author.is_seacher %}
                                        <a href="#">Chercheur</a>
                                    {% else %}
                                        <a href="">Non précisé</a>
                                    {% endif %}
                                        
                                    </p>
                                    <h3 class="card-title">
                                        <a href="#"> {{document.title}} </a>
                                    </h3>
                                    <p class="card-text">
                                    {{document.description}}
                                    </p>
                                    {% if document.document_type == 'Thesis' %}
                                        <a href="{% url 'app:document_details' 'thesis' document.id %}" class="btn btn-primary btn-rounded btn-sm"
                                    >Voir plus</a
                                    >
                                    {% elif document.document_type == 'Memory' %}
                                        <a href="{% url 'app:document_details' 'memory' document.id %}" class="btn btn-primary btn-rounded btn-sm"
                                        >Voir plus</a
                                        >
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        {% endfor %}
                        {% else %}
                         <p>
                            Pas des publications trouvées 
                         </p>
                        {% endif %}
                            
                     
                        {% comment %} ------------------------------------ {% endcomment %}
                   
                    </div>
                    
                </div>
            </div>
    </div>
</div>




    
{% endblock container %}
    

templates/app/site/pages/view_these.html
{% extends "app/site/base.html" %}
{% load static %}

{% block container %}
<div class="page-inner">
   <div class="page-header">
        <h3 class="fw-bold mb-3">Thèses</h3>
        <ul class="breadcrumbs mb-3">
            <li class="nav-home">
                <a href="{% url 'app:home' %}">
                    <i class="icon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="icon-arrow-right"></i>
            </li>
            <li class="nav-item">
                <a href="#">Documents</a>
            </li>
            <li class="separator">
                <i class="icon-arrow-right"></i>
            </li>
            <li class="nav-item">
                <a href="{% url 'app:view_thesis' %}">Thèses</a>
            </li>
        </ul>

         <div class="ms-md-auto py-2 py-md-0">
            <a href="{% url 'app:add_thesis' %}" class="btn btn-label-info btn-round me-2">Publier</a>
        </div>

    </div>  
    
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Toutes les thèses</div>
                </div>
                <div class="card-body">
                    {% comment %} Les cartes {% endcomment %}
                    <div class="row">
                        {% comment %} ------------------------------------ {% endcomment %}
                        
                        {% if documents %}
                        {% for document in documents %}
                        <div class="col-md-4">
                            <div class="card card-post card-round">
                                <img
                                    class="card-img-top"
                                    src="{{document.image.url}}"
                                    alt="Card image cap"
                                />
                                <div class="card-body">
                                    <div class="d-flex">
                                        <div class="avatar">
                                            {% if  document.author.profile_photo %}
                                            <img
                                            src={{document.author.profile_photo.url}}
                                            alt="..."
                                            class="avatar-img rounded-circle"
                                            />
                                            {% else %}
                                              <i class="fas fa-user fs-5"></i>
                                            {% endif %}
                                          
                                        </div>
                                        <div class="info-post ms-2">
                                            <p class="username">{{document.author.username}} 
                                            {% if user == document.author %}
                                                <small class="ml-2">(Vous)</small>
                                            {% endif %}
                                                </p>
                                            <p class="date text-muted">{{document.date_publication}}</p>
                                        </div>
                                    </div>
                                    <div class="separator-solid"></div>
                                    <p class="card-category text-info mb-1">
                                    
                                    {% if document.author.is_student %}
                                        <a href="#">Etudiant</a> 
                                    {% elif document.author.is_academic_personal %}
                                        <a href="#">Personel Académique</a>
                                    {% elif document.author.is_seacher %}
                                        <a href="#">Chercheur</a>
                                    {% else %}
                                    <a href="">Non précisé</a>
                                    {% endif %}
                                        
                                    </p>
                                    <h3 class="card-title">
                                    <a href="#"> {{document.title}} </a>
                                    </h3>
                                    <p class="card-text">
                                    {{document.description}}
                                    </p>
                                    {% if document.document_type == 'Thesis' %}
                                        <a href="{% url 'app:document_details' 'thesis' document.id %}" class="btn btn-primary btn-rounded btn-sm"
                                    >Voir plus</a
                                    >
                                    {% elif document.document_type == 'Memory' %}
                                        <a href="{% url 'app:document_details' 'memory' document.id %}" class="btn btn-primary btn-rounded btn-sm"
                                        >Voir plus</a
                                        >
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        {% endfor %}
                        {% else %}
                         <p>
                            Pas des publications trouvées 
                         </p>
                        {% endif %}
                            
                     
                        {% comment %} ------------------------------------ {% endcomment %}
                   
                    </div>
                    
                </div>
            </div>
    </div>
</div>




    
{% endblock container %}
    